<?php

return [
    [
        "regione" => "Lombarida",
        "provincia"=> "Milano",
        "id" => 1,
        "comuni"=>[
            "Abbiategrasso",
            "Albairate",
            "Arconate",
            "Arese",
            "Arluno",
            "Assago",
            "Baranzate",
            "Bareggio",
            "Basiano",
            "Basiglio",
            "Bellinzago Lombardo",
            "Bernate Ticino",
            "Besate",
            "Binasco",
            "Boffalora sopra Ticino",
            "Bollate",
            "Bresso",
            "Bubbiano",
            "Buccinasco",
            "Buscate",
            "Bussero",
            "Busto Garolfo",
            "Calvignasco",
            "Cambiago",
            "Canegrate",
            "Carpiano",
            "Carugate",
            "Casarile",
            "Casorezzo",
            "Cassano d'Adda",
            "Cassina de' Pecchi",
            "Cassinetta di Lugagnano",
            "Castano Primo",
            "Cernusco sul Naviglio",
            "Cerro al Lambro",
            "Cerro Maggiore",
            "Cesano Boscone",
            "Cesate",
            "Cinisello Balsamo",
            "Cisliano",
            "Cologno Monzese",
            "Colturano",
            "Corbetta",
            "Cormano",
            "Cornaredo",
            "Corsico",
            "Cuggiono",
            "Cusago",
            "Cusano Milanino",
            "Dairago",
            "Dresano",
            "Gaggiano",
            "Garbagnate Milanese",
            "Gessate",
            "Gorgonzola",
            "Grezzago",
            "Gudo Visconti",
            "Inveruno",
            "Inzago",
            "Lacchiarella",
            "Lainate",
            "Legnano",
            "Liscate",
            "Locate di Triulzi",
            "Magenta",
            "Magnago",
            "Marcallo con Casone",
            "Masate",
            "Mediglia",
            "Melegnano",
            "Melzo",
            "Mesero",
            "MILANO",
            "Morimondo",
            "Motta Visconti",
            "Nerviano",
            "Nosate",
            "Novate Milanese",
            "Noviglio",
            "Opera",
            "Ossona",
            "Ozzero",
            "Paderno Dugnano",
            "Pantigliate",
            "Parabiago",
            "Paullo",
            "Pero",
            "Peschiera Borromeo",
            "Pessano con Bornago",
            "Pieve Emanuele",
            "Pioltello",
            "Pogliano Milanese",
            "Pozzo d'Adda",
            "Pozzuolo Martesana",
            "Pregnana Milanese",
            "Rescaldina",
            "Rho",
            "Robecchetto con Induno",
            "Robecco sul Naviglio",
            "Rodano",
            "Rosate",
            "Rozzano",
            "San Colombano al Lambro",
            "San Donato Milanese",
            "San Giorgio su Legnano",
            "San Giuliano Milanese",
            "San Vittore Olona",
            "San Zenone al Lambro",
            "Santo Stefano Ticino",
            "Sedriano",
            "Segrate",
            "Senago",
            "Sesto San Giovanni",
            "Settala",
            "Settimo Milanese",
            "Solaro",
            "Trezzano Rosa",
            "Trezzano sul Naviglio",
            "Trezzo sull'Adda",
            "Tribiano",
            "Truccazzano",
            "Turbigo",
            "Vanzaghello",
            "Vanzago",
            "Vaprio d'Adda",
            "Vermezzo con Zelo",
            "Vernate",
            "Vignate",
            "Villa Cortese",
            "Vimodrone",
            "Vittuone",
            "Vizzolo Predabissi",
            "Zibido San Giacomo"
        ]
    ],
    [
        "regione" => "Lombarida",
        "provincia"=> "Bergamo",
        "id" => 2,
        "comuni"=>[
            "Adrara San Martino",
            "Adrara San Rocco",
            "Albano Sant'Alessandro",
            "Albino",
            "Algua",
            "Almè",
            "Almenno San Bartolomeo",
            "Almenno San Salvatore",
            "Alzano Lombardo",
            "Ambivere",
            "Antegnate",
            "Arcene",
            "Ardesio",
            "Arzago d'Adda",
            "Averara",
            "Aviatico",
            "Azzano San Paolo",
            "Azzone",
            "Bagnatica",
            "Barbata",
            "Bariano",
            "Barzana",
            "Bedulita",
            "Berbenno",
            "BERGAMO",
            "Berzo San Fermo",
            "Bianzano",
            "Blello",
            "Bolgare",
            "Boltiere",
            "Bonate Sopra",
            "Bonate Sotto",
            "Borgo di Terzo",
            "Bossico",
            "Bottanuco",
            "Bracca",
            "Branzi",
            "Brembate",
            "Brembate di Sopra",
            "Brignano Gera d'Adda",
            "Brumano",
            "Brusaporto",
            "Calcinate",
            "Calcio",
            "Calusco d'Adda",
            "Calvenzano",
            "Camerata Cornello",
            "Canonica d'Adda",
            "Capizzone",
            "Capriate San Gervasio",
            "Caprino Bergamasco",
            "Caravaggio",
            "Carobbio degli Angeli",
            "Carona",
            "Carvico",
            "Casazza",
            "Casirate d'Adda",
            "Casnigo",
            "Cassiglio",
            "Castel Rozzone",
            "Castelli Calepio",
            "Castione della Presolana",
            "Castro",
            "Cavernago",
            "Cazzano Sant'Andrea",
            "Cenate Sopra",
            "Cenate Sotto",
            "Cene",
            "Cerete",
            "Chignolo d'Isola",
            "Chiuduno",
            "Cisano Bergamasco",
            "Ciserano",
            "Cividate al Piano",
            "Clusone",
            "Colere",
            "Cologno al Serio",
            "Colzate",
            "Comun Nuovo",
            "Corna Imagna",
            "Cornalba",
            "Cortenuova",
            "Costa di Mezzate",
            "Costa Serina",
            "Costa Valle Imagna",
            "Costa Volpino",
            "Covo",
            "Credaro",
            "Curno",
            "Cusio",
            "Dalmine",
            "Dossena",
            "Endine Gaiano",
            "Entratico",
            "Fara Gera d'Adda",
            "Fara Olivana con Sola",
            "Filago",
            "Fino del Monte",
            "Fiorano al Serio",
            "Fontanella",
            "Fonteno",
            "Foppolo",
            "Foresto Sparso",
            "Fornovo San Giovanni",
            "Fuipiano Valle Imagna",
            "Gandellino",
            "Gandino",
            "Gandosso",
            "Gaverina Terme",
            "Gazzaniga",
            "Ghisalba",
            "Gorlago",
            "Gorle",
            "Gorno",
            "Grassobbio",
            "Gromo",
            "Grone",
            "Grumello del Monte",
            "Isola di Fondra",
            "Isso",
            "Lallio",
            "Leffe",
            "Lenna",
            "Levate",
            "Locatello",
            "Lovere",
            "Lurano",
            "Luzzana",
            "Madone",
            "Mapello",
            "Martinengo",
            "Medolago",
            "Mezzoldo",
            "Misano di Gera d'Adda",
            "Moio de' Calvi",
            "Monasterolo del Castello",
            "Montello",
            "Morengo",
            "Mornico al Serio",
            "Mozzanica",
            "Mozzo",
            "Nembro",
            "Olmo al Brembo",
            "Oltre il Colle",
            "Oltressenda Alta",
            "Oneta",
            "Onore",
            "Orio al Serio",
            "Ornica",
            "Osio Sopra",
            "Osio Sotto",
            "Pagazzano",
            "Paladina",
            "Palazzago",
            "Palosco",
            "Parre",
            "Parzanica",
            "Pedrengo",
            "Peia",
            "Pianico",
            "Piario",
            "Piazza Brembana",
            "Piazzatorre",
            "Piazzolo",
            "Pognano",
            "Ponte Nossa",
            "Ponte San Pietro",
            "Ponteranica",
            "Pontida",
            "Pontirolo Nuovo",
            "Pradalunga",
            "Predore",
            "Premolo",
            "Presezzo",
            "Pumenengo",
            "Ranica",
            "Ranzanico",
            "Riva di Solto",
            "Rogno",
            "Romano di Lombardia",
            "Roncobello",
            "Roncola",
            "Rota d'Imagna",
            "Rovetta",
            "San Giovanni Bianco",
            "San Paolo d'Argon",
            "San Pellegrino Terme",
            "Sant'Omobono Terme",
            "Santa Brigida",
            "Sarnico",
            "Scanzorosciate",
            "Schilpario",
            "Sedrina",
            "Selvino",
            "Seriate",
            "Serina",
            "Solto Collina",
            "Solza",
            "Songavazzo",
            "Sorisole",
            "Sotto il Monte G. XXIII",
            "Sovere",
            "Spinone al Lago",
            "Spirano",
            "Stezzano",
            "Strozza",
            "Suisio",
            "Taleggio",
            "Tavernola Bergamasca",
            "Telgate",
            "Terno d'Isola",
            "Torre Boldone",
            "Torre de' Busi",
            "Torre de' Roveri",
            "Torre Pallavicina",
            "Trescore Balneario",
            "Treviglio",
            "Treviolo",
            "Ubiale Clanezzo",
            "Urgnano",
            "Val Brembilla",
            "Valbondione",
            "Valbrembo",
            "Valgoglio",
            "Valleve",
            "Valnegra",
            "Valtorta",
            "Vedeseta",
            "Verdellino",
            "Verdello",
            "Vertova",
            "Viadanica",
            "Vigano San Martino",
            "Vigolo",
            "Villa d'Adda",
            "Villa d'Almè",
            "Villa d'Ogna",
            "Villa di Serio",
            "Villongo",
            "Vilminore di Scalve",
            "Zandobbio",
            "Zanica",
            "Zogno"
        ]
    ],
    [
        "regione" => "Lombarida",
        "provincia"=> "Como",
        "id" => 3,
        "comuni"=>[
            "Albavilla",
            "Albese con Cassano",
            "Albiolo",
            "Alserio",
            "Alta Valle Intelvi",
            "Alzate Brianza",
            "Anzano del Parco",
            "Appiano Gentile",
            "Argegno",
            "Arosio",
            "Asso",
            "Barni",
            "Bellagio",
            "Bene Lario",
            "Beregazzo con Figliaro",
            "Binago",
            "Bizzarone",
            "Blessagno",
            "Blevio",
            "Bregnano",
            "Brenna",
            "Brienno",
            "Brunate",
            "Bulgarograsso",
            "Cabiate",
            "Cadorago",
            "Caglio",
            "Campione d'Italia",
            "Cantù",
            "Canzo",
            "Capiago Intimiano",
            "Carate Urio",
            "Carbonate",
            "Carimate",
            "Carlazzo",
            "Carugo",
            "Caslino d'Erba",
            "Casnate con Bernate",
            "Cassina Rizzardi",
            "Castelmarte",
            "Castelnuovo Bozzente",
            "Cavargna",
            "Centro Valle Intelvi",
            "Cerano d'Intelvi",
            "Cermenate",
            "Cernobbio",
            "Cirimido",
            "Claino con Osteno",
            "Colonno",
            "Colverde",
            "COMO",
            "Corrido",
            "Cremia",
            "Cucciago",
            "Cusino",
            "Dizzasco",
            "Domaso",
            "Dongo",
            "Dosso del Liro",
            "Erba",
            "Eupilio",
            "Faggeto Lario",
            "Faloppio",
            "Fenegrò",
            "Figino Serenza",
            "Fino Mornasco",
            "Garzeno",
            "Gera Lario",
            "Grandate",
            "Grandola ed Uniti",
            "Gravedona ed Uniti",
            "Griante",
            "Guanzate",
            "Inverigo",
            "Laglio",
            "Laino",
            "Lambrugo",
            "Lasnigo",
            "Lezzeno",
            "Limido Comasco",
            "Lipomo",
            "Livo",
            "Locate Varesino",
            "Lomazzo",
            "Longone al Segrino",
            "Luisago",
            "Lurago d'Erba",
            "Lurago Marinone",
            "Lurate Caccivio",
            "Magreglio",
            "Mariano Comense",
            "Maslianico",
            "Menaggio",
            "Merone",
            "Moltrasio",
            "Monguzzo",
            "Montano Lucino",
            "Montemezzo",
            "Montorfano",
            "Mozzate",
            "Musso",
            "Nesso",
            "Novedrate",
            "Olgiate Comasco",
            "Oltrona di San Mamette",
            "Orsenigo",
            "Peglio",
            "Pianello del Lario",
            "Pigra",
            "Plesio",
            "Pognana Lario",
            "Ponna",
            "Ponte Lambro",
            "Porlezza",
            "Proserpio",
            "Pusiano",
            "Rezzago",
            "Rodero",
            "Rovellasca",
            "Rovello Porro",
            "Sala Comacina",
            "San Bartolomeo Val C.",
            "San Fermo della Battaglia",
            "San Nazzaro Val Cavargna",
            "San Siro",
            "Schignano",
            "Senna Comasco",
            "Solbiate con Cagno",
            "Sorico",
            "Sormano",
            "Stazzona",
            "Tavernerio",
            "Torno",
            "Tremezzina",
            "Trezzone",
            "Turate",
            "Uggiate con Ronago",
            "Val Rezzo",
            "Valbrona",
            "Valmorea",
            "Valsolda",
            "Veleso",
            "Veniano",
            "Vercana",
            "Vertemate con Minoprio",
            "Villa Guardia",
            "Zelbio"
        ]
    ],

];